# Generated by Django 4.2.7 on 2024-04-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.TextField(choices=[('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Withdrawn', 'Withdrawn'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Under Review'),
        ),
    ]
